name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Let us know how we can improve.

  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: What feature would you like to see? Why is it useful?
      placeholder: For example: Add ability to export reports to PDF...
    validations:
      required: true

  - type: input
    id: screenshots
    attributes:
      label: Screenshots or references (optional)
      description: Provide a link to an image or attach it after submitting, if applicable.
      placeholder: https://link.to/example-image
